///
/// @Generated by Mockolo
///

import Core
import Foundation

public class EndpointProviderMock: EndpointProvider {
    public init() { }
    public private(set) var urlCallCount = 0
    public var urlHandler: ((Endpoint, [CVarArg]) -> (URL?))?
    public func url(for endpoint: Endpoint, with args: [CVarArg]) -> URL? {
        urlCallCount += 1
        if let urlHandler = urlHandler {
            return urlHandler(endpoint, args)
        }
        return nil
    }
}
