///
/// @Generated by Mockolo
///

import Core
import UIKit

public class ImageCacheProviderMock: ImageCacheProvider {
    public init() { }
    public private(set) var saveCallCount = 0
    public var saveHandler: ((UIImage, URL) -> ())?
    public func save(_ image: UIImage, for url: URL)  {
        saveCallCount += 1
        if let saveHandler = saveHandler {
            saveHandler(image, url)
        }
    }

    public private(set) var retrieveCallCount = 0
    public var retrieveHandler: ((URL) -> (UIImage?))?
    public func retrieve(_ url: URL) -> UIImage? {
        retrieveCallCount += 1
        if let retrieveHandler = retrieveHandler {
            return retrieveHandler(url)
        }
        return nil
    }
}

