///
/// @Generated by Mockolo
///

import Combine
import Core
import Foundation

public class OnlinePostProviderMock: OnlinePostProvider {
    public init() { }

    public private(set) var fetchPostsCallCount = 0
    public var fetchPostsHandler: ((Post?) -> (AnyPublisher<[Post], DataError>))?
    public func fetchPosts(afterPost: Post?) -> AnyPublisher<[Post], DataError> {
        fetchPostsCallCount += 1
        if let fetchPostsHandler = fetchPostsHandler {
            return fetchPostsHandler(afterPost)
        }
        fatalError("fetchPostsHandler returns can't have a default value thus its handler must be set")
    }
}
