///
/// @Generated by Mockolo
///

import Combine
import Core
import Foundation

public class RequestProviderMock: RequestProvider {
    public init() { }

    public private(set) var requestCallCount = 0
    public var requestHandler: ((Endpoint, CVarArg...) -> (AnyPublisher<Data, DataError>))?
    public func request(endpoint: Endpoint, with args: CVarArg...) -> AnyPublisher<Data, DataError> {
        requestCallCount += 1
        if let requestHandler = requestHandler {
            return requestHandler(endpoint, args)
        }
        fatalError("requestHandler returns can't have a default value thus its handler must be set")
    }

    public private(set) var requestUrlCallCount = 0
    public var requestUrlHandler: ((URL) -> (AnyPublisher<Data, DataError>))?
    public func request(url: URL) -> AnyPublisher<Data, DataError> {
        requestUrlCallCount += 1
        if let requestUrlHandler = requestUrlHandler {
            return requestUrlHandler(url)
        }
        fatalError("requestUrlHandler returns can't have a default value thus its handler must be set")
    }
}
